### ISSUE TITLE
Change efficacy parameter to facilitate LR/HR vaccination strategies

### ISSUE THREAD

**Issue by dthorrington** [MJomaba/flu-evidence-synthesis#44]
The efficacy parameter that goes in to the vaccine calendar is currently a list of 3 items (one per strain), with vaccine efficacy for 7 age groups over the 14 years of data. But this does not allow us to differentiate between different vaccination programmes for low-risk and high-risk individuals.

Can the dimensions of the efficacy parameter be changed so that we can simulate the introduction of two vaccination programmes of different efficacy based on the LR/HR status of individuals?

**Comment by BlackEdder** [comment]
I also updated the vaccination vignette to use the new method. Might be if interest. @dthorrington
